support encode default values
starwing/lua-protobuf pull request #158
Opened 2021-09-02 04:19 UTC by sundream

use pb.option "enable_encode_default_values" and pb.option "no_default_values" can distinguish 'default value' and 'nil'
see #136

2021-09-03 09:46 UTC, starwing commented
这个option的具体语义是啥……？

2021-09-03 10:52 UTC, sundream commented
enable_encode_default_values含义是: 编码时默认值也参与序列化,这样解码时结合no_default_values语义就能区分: 编码时是传递了默认值还是传nil了

2021-09-04 02:05 UTC, starwing commented
那可以考虑去掉"enable_"，不然选项太长了。另外可能需要看看这个选项和一堆default_values选项的正交性，看看有没有机会合并进其他选项，最后还需要更新一下文档。这些都OK了应该就可以合并了，然后我来出个新版本~多谢贡献代码！

2021-09-04 02:20 UTC, starwing requested changes

2021-09-04 02:20 UTC, starwing commented on pb.c
> +    lpb_State *LS = e->LS;
这里可以考虑直接修改下面的判断条件，不用改ignorezero变量的值

2021-09-04 02:20 UTC, starwing commented on pb.c
> +        if (LS->encode_default_values) {
这个感觉是额外的语义了，和encode不相关，可以考虑加个新的选项控制

2021-09-04 02:20 UTC, starwing commented on pb.c
> +    X(12, disable_encode_default_values,        LS->encode_default_values = 0)      \
hook是作为功能开关的，所以是`enable`/`disable`，这个选项更多的是编码解码选项而不是某个功能的开关，直接`encode_default_values`/`no_encode_default_values`可能更好一些。

2021-09-06 03:04 UTC, sundream commented
改了,增加了两个选项
| `encode_default_values` | 默认值也参与编码 |
| `decode_default_array`  | 对于数组,将空值解码为空表 |

2021-09-06 03:57 UTC, starwing commented
好像没加对应的`no_`选项？另外嵌套if那块可以改成&&串联，这样（我个人觉得，当然不改也无所谓）看起来清晰些。最后加上对应`no_`选项的文档就合并啦~多谢了~

2021-09-06 06:07 UTC, sundream commented
no_选项是默认值,加了好像有点多余,确定需要?,我可以加下

2021-09-07 04:56 UTC, starwing approved these changes

2021-09-07 04:58 UTC, merged

2021-09-07 05:00 UTC, starwing commented
已合并！多谢~